version: '2'

services:
  app:
    image: ghcr.io/kosipov/students:main
    restart: always
    environment:
      - MYSQL_HOST=$MYSQL_HOST
      - MYSQL_USERNAME=$MYSQL_USERNAME
      - MYSQL_DBNAME=$MYSQL_DBNAME
      - GIN_MODE=$GIN_MODE
    ports:
      - "8080:8080"
    networks:
      - "bridge"