on:
  push:
    branches:
      - main

jobs:

  build_and_push:
    name: Build, push, and deploy Docker image to DO Container Registry
    runs-on: ubuntu-latest
    steps:

      - name: Checkout main
        uses: actions/checkout@main

      - name: Build container image latest version
        run: docker build -t ghcr.io/kosipov/student:latest .

      - name: Push image to DigitalOcean Container Registry
        run: docker push ghcr.io/kosipov/student:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - name: Deploy to my vps via SSH action
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd student.app
            export MYSQL_HOST ${{ secrets.MYSQL_HOST }}
            export MYSQL_USER ${{ secrets.MYSQL_USERNAME }}
            export MYSQL_DBNAME ${{ secrets.MYSQL_DBNAME }}
            export GIN_MODE release
            echo ${{secrets.DOCKER_HUB_GITHUB_KEY}} | docker login ghcr.io -u USERNAME --password-stdin
            docker-compose stop
            docker-compose rm -f
            docker-compose pull
            docker-compose up -d